### ISSUE TITLE
Migrate to deno 2?

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#165]

**Comment by Muhammed-Rahif** [comment]
https://github.com/electron/electron/issues/23613

**Comment by Muhammed-Rahif** [comment]
As per #167 electron is no more on this project, the deno idea has a point.
A related to issue on deno side for running sveltekit (https://github.com/denoland/deno/issues/17757): 
```js
error: Uncaught Error: Too many open files (os error 24)
    at new FsWatcher (ext:runtime/40_fs_events.js:31:17)
    at Object.watchFs (ext:runtime/40_fs_events.js:93:10)
    at ext:deno_node/_fs/_fs_watch.ts:57:21
    at callback (ext:deno_web/02_timers.js:68:7)
    at eventLoopTick (ext:core/01_core.js:210:13)
```

**Comment by Muhammed-Rahif** [comment]
Workaround for now: https://github.com/denoland/deno/issues/17757#issuecomment-1870211014

**Comment by Muhammed-Rahif** [comment]
Migrating deno is temporarily not planned.
